Add model relationships and associated test cases
Watt-Dev/snapthat-api pull request #2
Opened 2021-01-18 20:17 UTC by calumshep

2021-01-19 09:53 UTC, wrt95 requested changes

2021-01-19 09:53 UTC, wrt95 commented on app/Models/Post.php
>          'channel_id',
Is rating deleted?

2021-01-19 10:44 UTC, calumshep commented on app/Models/Post.php
>          'channel_id',
No, this is an array of assets which are 'mass-assignable' when updating the Post model. Since the rating should only ever change when up/downvoting a post, it does not need to be mass-assigned (changed along with other properties) and it defaults to 0 in the database, so it's not needed in this array (kind of an extra layer of protection to ensure posts are initialised with rating 0)

2021-01-19 10:47 UTC, wrt95 commented on app/Models/Post.php
>          'channel_id',
Ah okey, makes sense!

2021-01-19 10:47 UTC, wrt95 approved these changes

2021-01-20 16:09 UTC, wrt95 approved these changes

2021-01-20 16:10 UTC, merged